# Generated by Django 5.2.17 on 2026-09-25 08:15

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザーID')),
                ('display_name', models.CharField(max_length=150, verbose_name='表示名')),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_admin', models.BooleanField(default=False, verbose_name='システム管理者')),
                ('is_special', models.BooleanField(default=False)),
                ('must_change_password', models.BooleanField(default=True)),
                ('temporary_password_expires_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_active', False), ('is_special', True), ('is_system_admin', False), ('username', 'unknown')), models.Q(('is_special', False), models.Q(('username', 'unknown'), _negated=True)), _connector='OR'), name='reserved_unknown')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_snapshot', models.JSONField(default=dict)),
                ('project_id', models.BigIntegerField(null=True)),
                ('entity_type', models.CharField(max_length=40)),
                ('entity_id', models.BigIntegerField()),
                ('entity_snapshot', models.JSONField(default=dict)),
                ('action', models.CharField(max_length=40)),
                ('changes', models.JSONField(default=dict)),
                ('ticket_context_id', models.BigIntegerField(null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'occurred_at'], name='audit_event_entity__9f336a_idx')],
            },
        ),
    ]
