# Generated by Django 5.2.17 on 2026-09-28 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('description_markdown', models.TextField(blank=True, max_length=100000, verbose_name='説明（Markdown）')),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=6, verbose_name='優先度')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='開始日')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='tickets.ticket')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.ticketstatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projects.tickettype')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['project', '-updated_at', '-id'], name='tickets_project_39cd39_idx'), models.Index(fields=['assignee', '-updated_at', '-id'], name='tickets_assigne_53b9a3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('due_date__isnull', True), ('start_date__lte', models.F('due_date')), _connector='OR'), name='ticket_date_order'), models.CheckConstraint(condition=models.Q(('priority__in', ['high', 'medium', 'low'])), name='ticket_priority'), models.CheckConstraint(condition=models.Q(('parent_id', models.F('id')), _negated=True), name='ticket_not_own_parent')],
            },
        ),
    ]
